ANIMA: animaComputeDTIScalarMaps.cxx File Reference
animaComputeDTIScalarMaps.cxx File Reference
#include <animaDTIScalarMapsImageFilter.h>
#include <tclap/CmdLine.h>
#include <itkImage.h>
#include <itkImageFileReader.h>
#include <itkImageFileWriter.h>
#include <itkCommand.h>
#include <animaReadWriteFunctions.h>
Functions
void eventCallback (itk::Object *caller, const itk::EventObject &event, void *clientData)
int main (int ac, const char **av)
Function Documentation
void eventCallback (itk::Object * caller, const itk::EventObject & event, void * clientData)
Definition at line 13 of file animaComputeDTIScalarMaps.cxx.
Referenced by anima::HierarchicalInitializer< TInputImage, TMaskImage >::ComputeSolution1D(), extract(), main(), and anima::ComputeSolution< TInputImage, TMaskImage, TAtlasImage >::Update().
int main (int ac, const char ** av)
Definition at line 20 of file animaComputeDTIScalarMaps.cxx.
References eventCallback().