ANIMA: anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType > Class Template Reference
anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType > Class Template Reference
#include <animaTensorResampleImageFilter.h>
Public Types
typedef itk::SmartPointer
< const Self > ConstPointer
typedef Superclass::InputImageType InputImageType
typedef Superclass::InputPixelType InputPixelType
typedef itk::SmartPointer< Self > Pointer
typedef TensorResampleImageFilter Self
typedef
OrientedModelBaseResampleImageFilter
< TImageType,
TInterpolatorPrecisionType > Superclass
Public Types inherited from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >
typedef itk::SmartPointer
< const Self > ConstPointer
typedef
InterpolatorType::ContinuousIndexType ContinuousIndexType
typedef TOutputImage::DirectionType DirectionType
typedef GeometryImageType::Pointer GeometryImagePointer
typedef itk::Image< unsigned
char, itkGetStaticConstMacro(ImageDimension)> GeometryImageType
typedef InputImageType::Pointer InputImagePointer
typedef TImageType InputImageType
typedef InputImageType::IndexType InputIndexType
typedef InputImageType::PixelType InputPixelType
typedef InterpolatorType::Pointer InterpolatorPointer
typedef
itk::InterpolateImageFunction
< InputImageType,
TInterpolatorPrecisionType > InterpolatorType
typedef
itk::MatrixOffsetTransformBase
< TInterpolatorPrecisionType,
itkGetStaticConstMacro(ImageDimension),
itkGetStaticConstMacro(ImageDimension)> MatrixTransformType
typedef TOutputImage::PointType OriginPointType
typedef TOutputImage::Pointer OutputImagePointer
typedef TOutputImage::RegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef InterpolatorType::PointType PointType
typedef TOutputImage::RegionType RegionType
typedef
OrientedModelBaseResampleImageFilter Self
typedef TOutputImage::SpacingType SpacingType
typedef
itk::ImageToImageFilter
< TImageType, TImageType > Superclass
typedef TImageType TOutputImage
typedef TransformType::Pointer TransformPointer
typedef itk::Transform
< TInterpolatorPrecisionType,
itkGetStaticConstMacro(ImageDimension),
itkGetStaticConstMacro(ImageDimension)> TransformType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
Public Member Functions inherited from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >
virtual bool GetFiniteStrainReorientation ()
virtual InterpolatorType * GetInterpolator ()
virtual const DirectionType & GetOutputDirection () const
virtual const RegionType & GetOutputLargestPossibleRegion () const
virtual const OriginPointType & GetOutputOrigin () const
virtual const SpacingType & GetOutputSpacing () const
virtual TransformType * GetTransform ()
virtual void SetFiniteStrainReorientation (bool _arg)
virtual void SetInterpolator (InterpolatorPointer _arg)
virtual void SetOutputDirection (DirectionType _arg)
virtual void SetOutputLargestPossibleRegion (RegionType _arg)
virtual void SetOutputOrigin (OriginPointType _arg)
virtual void SetOutputSpacing (SpacingType _arg)
void SetTransform (TransformType *trsf)
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int ImageDimension = InputImageType::ImageDimension
Static Public Attributes inherited from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >
static const unsigned int ImageDimension = InputImageType::ImageDimension
Protected Member Functions
virtual void BeforeThreadedGenerateData () ITK_OVERRIDE
virtual void ReorientInterpolatedModel (const InputPixelType &interpolatedModel, vnl_matrix< double > &modelOrientationMatrix, InputPixelType &rotatedModel, itk::ThreadIdType threadId) ITK_OVERRIDE
Needs to be implemented in sub-classes, does the actual re-orientation of the model.
TensorResampleImageFilter ()
virtual ~TensorResampleImageFilter ()
Protected Member Functions inherited from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >
vnl_matrix< double > ComputeLinearJacobianMatrix ()
void ComputeLocalJacobianMatrix (InputIndexType &index, vnl_matrix< double > &reorientationMatrix)
virtual void ComputeRotationParametersFromReorientationMatrix (vnl_matrix< double > &reorientationMatrix, vnl_matrix< double > &modelOrientationMatrix)
virtual unsigned int GetOutputVectorLength ()
virtual void InitializeInterpolator ()
Initializes the default interpolator, might change in derived classes.
template<class T >
void InitializeZeroPixel (itk::VariableLengthVector< T > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
template<class T >
void InitializeZeroPixel (T &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
template<class T >
bool isZero (itk::VariableLengthVector< T > &dataVec)
template<class T >
bool isZero (T &data)
void LinearThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId)
void NonLinearThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId)
OrientedModelBaseResampleImageFilter ()
void ThreadedGenerateData (const OutputImageRegionType &outputRegionForThread, itk::ThreadIdType threadId) ITK_OVERRIDE
virtual ~OrientedModelBaseResampleImageFilter ()
Detailed Description
template<typename TImageType, typename TInterpolatorPrecisionType = float>
class anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >
Definition at line 9 of file animaTensorResampleImageFilter.h.
Member Typedef Documentation
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef itk::SmartPointer<const Self> anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ConstPointer
Definition at line 18 of file animaTensorResampleImageFilter.h.
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef Superclass::InputImageType anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InputImageType
Definition at line 21 of file animaTensorResampleImageFilter.h.
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef Superclass::InputPixelType anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::InputPixelType
Definition at line 20 of file animaTensorResampleImageFilter.h.
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef itk::SmartPointer<Self> anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::Pointer
Definition at line 17 of file animaTensorResampleImageFilter.h.
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef TensorResampleImageFilter anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::Self
Standard class typedefs.
Definition at line 14 of file animaTensorResampleImageFilter.h.
template<typename TImageType , typename TInterpolatorPrecisionType = float> typedef OrientedModelBaseResampleImageFilter<TImageType,TInterpolatorPrecisionType> anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::Superclass
Definition at line 16 of file animaTensorResampleImageFilter.h.
Constructor & Destructor Documentation
template<typename TImageType , typename TInterpolatorPrecisionType = float> anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::TensorResampleImageFilter () inline protected
Definition at line 31 of file animaTensorResampleImageFilter.h.
References anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ImageDimension.
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::~TensorResampleImageFilter () inline protected virtual
Definition at line 37 of file animaTensorResampleImageFilter.h.
Member Function Documentation
template<typename TImageType , typename TInterpolatorPrecisionType > void anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::BeforeThreadedGenerateData () protected virtual
Reimplemented from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
Definition at line 12 of file animaTensorResampleImageFilter.hxx.
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual::itk::LightObject::Pointer anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::CreateAnother (void) const
template<typename TImageType , typename TInterpolatorPrecisionType = float> virtual const char* anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
template<typename TImageType , typename TInterpolatorPrecisionType = float> static Pointer anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::New () static
Method for creation through the object factory.
template<typename TImageType , typename TInterpolatorPrecisionType > void anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ReorientInterpolatedModel (const InputPixelType & interpolatedModel, vnl_matrix< double > & modelOrientationMatrix, InputPixelType & orientedModel, itk::ThreadIdType threadId) protected virtual
Needs to be implemented in sub-classes, does the actual re-orientation of the model.
Implements anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
Definition at line 36 of file animaTensorResampleImageFilter.hxx.
References anima::ExtractPPDRotationFromJacobianMatrix(), anima::GetTensorFromVectorRepresentation(), anima::GetVectorRepresentation(), and anima::RotateSymmetricMatrix().
Member Data Documentation
template<typename TImageType , typename TInterpolatorPrecisionType = float> const unsigned int anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::ImageDimension = InputImageType::ImageDimension static
Definition at line 22 of file animaTensorResampleImageFilter.h.
Referenced by anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >::TensorResampleImageFilter().
The documentation for this class was generated from the following files:
animaTensorResampleImageFilter.h
animaTensorResampleImageFilter.hxx